language : android

jdk: 
 - oraclejdk8

addons: 
 apt:
  packages: 
   - oracle-java8-installer

# Global Reference Values for the file
env:
  global:
  #Android API Version for the code
   - ANDROID_API_LEVEL=27
   
  #Android API Version for the emulator 
   - EMULATOR_API_LEVEL=22
   
  #Android Build Tools Version
   - ANDROID_BUILD_TOOLS_VERSION=27.0.2
   
  #Install Timeout (by default 2min is not enough for slow computers)
   - ADB_INSTALL_TIMEOUT=20 

android:
 components:

    # Android SDK Tools
    - tools
    - platform-tools

    #repeat tools to get newer Android SDK Tools
    - tools 

    # The SDK version used to compile your project
    - android-$ANDROID_API_LEVEL

     # The SDK version used by emulator
    - android-$EMULATOR_API_LEVEL

     # The BuildTools version used by your project
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION

    # Specify at least one system image for emulator
    - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL

    # Additional components
    - extra-android-m2repository

before_install:
- yes | sdkmanager "platforms;android-27"
- yes | sdkmanager "platforms;android-26"

before_script:

- echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi armeabi-v7a
- emulator -avd test -no-skin -no-audio -no-window &
- android-wait-for-emulator
- adb shell input keyevent 82 & 
- cd MyNews
- ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash)

script: 
  - ./gradlew connectedAndroidTest